FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# RideTime

# Group Riders

## Rider detail [/riders/{id}]

+ Parameters
    + id (string)

        The ID of the rider.
    
### Rider detail [GET]

+ Response 200 (application/json)
    + Attributes (Rider)
        + rides (array[Ride])

# Group Rides

## Ride [/rides/{id}]
A ride contains information about start time, location, members etc..

+ Parameters
    + id (string)

        The ID of the desired ride.
    
### Ride detail [GET]

+ Response 200 (application/json)
    + Attributes (Ride)

## Rides [/rides{?limit}]

### List Rides [GET]

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `10`

+ Response 200 (application/json)
    + Attributes (array[Ride])

### Create a New Ride [POST]

+ Request (application/json)
    + Attributes (Ride Base)
        + location_id: 3 (number)

+ Response 201 (application/json)
    + Attributes (Ride)

    + Headers

            Location: /rides/2
        
# Group Locations 

## Locations [/locations{?frame}{?limit}]

### List all Locations [GET]
Returns a list of nearby locations.

+ Parameters
    + limit (number, optional)

        A limit on the number of objects to be returned. Limit can range
        between 1 and 100 items.

        + Default: `10`
        
    + frame (array[Location GPS], required)
        
        Array of two corners of the map between which to search

+ Response 200 (application/json)
    + Attributes (array[Location])


## Location [/locations/{id}{?difficulties}{?activity}]
Location describes its name and gps, difficulties in area (optional?), optionally with activity information in the location

### Location detail [GET]

+ Parameters
    + id: 1 (string, required)

        The ID of the desired location.
        
    + difficulties: true (boolean)
    
        Whether to include difficulties in list
        
    + activity: false (boolean)
    
        Return what's going on in location
            
+ Response 200 (application/json)
    + Attributes (Location)
    
# Data Structures

## Ride Base (object)
+ start_time: 1548143726 (number)
+ name: Alice lake ride (string)
+ description: Some sentence (string)
+ route: From here to there (string)
+ difficulty: 2 (enum[number])
    + Members
        + 0 - easy/green
        + 1 - intermediate/blue
        + 2 - difficult/black
        + 3 - expert/double black 
        + 4 - other
        
## Location Base (object)
+ id: 1 (number, required)
+ name: Alice lake (string, required)
+ gps (Location GPS, required)

## Location (Location Base)
+ difficulties: [ 0, 1, 2, 3, 4 ] (array[number])

## Ride (Ride Base)
+ id: 250FF (string, required)
+ created: 1415203908 (number) - Time stamp
+ riders: [ 165, 266, 6554 ] (array[number]) - List of rider IDs
+ location (Location Base) - Location detail

## Location GPS (object)
+ lat: 49.775666 (number)
+ lon:: `-123.123307` (number)

## Rider (object)
+ id (number, required)
+ name (string, required)
+ email (string, required)
+ phone (number)
+ friends (array[number])
+ profile_pic (string)
+ cover_pic (string)
+ home_locations (array[Location Base]) - location IDs