version: "2" # required to adjust maintainability checks
checks:
  similar-code:
    config:
      threshold: 80 # Accomodates *similar* component props
  identical-code:
    config:
      threshold: 45